### ISSUE TITLE
Does not correctly validate coordination numbers

### ISSUE THREAD

**Issue by buren** [jonathanp/swedish-personal-identity-number-validator#1]
This is a valid (temporary) personal number (a.k.a samordningsnummer) `701063-2391` – notice that the day has been incremented by `60`, see https://www.skatteverket.se/privat/skatter/internationellt/bosattutomlands/samordningsnummer.4.53a97fe91163dfce2da80001279.html for more details.

**Comment by svenheden** [comment]
Tack! Ska fixa :)

**Comment by svenheden** [comment]
Fixat i cc81847c63871f0a4ece6a5b93bfffdfe0874c64
